/* This file was generated by the Hex-Rays decompiler version 8.4.0.240320.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
int sub_8048400();
// int printf(const char *format, ...);
// void free(void *ptr);
// char *strdup(const char *s);
// char *fgets(char *s, int n, FILE *stream);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// char *strcpy(char *dest, const char *src);
// void *malloc(size_t size);
// int system(const char *command);
// int __gmon_start__(void); weak
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _do_global_dtors_aux();
int frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
int _CTOR_LIST__[] = { -1 }; // weak
int _DTOR_LIST__[] = { -1 }; // weak
int _DTOR_END__ = 0; // weak
int _JCR_LIST__ = 0; // weak
Elf32_Dyn *GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_8049A34)(void) = NULL; // weak
FILE *stdin; // idb
FILE *stdout; // idb
char completed_6159; // weak
int dtor_idx_6161; // weak
char *auth; // idb
int service; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (080483C4) --------------------------------------------------------
void (*init_proc())(void)
{
  if ( &_gmon_start__ )
    __gmon_start__();
  frame_dummy();
  return _do_global_ctors_aux();
}
// 8048490: using guessed type int __gmon_start__(void);

//----- (08048400) --------------------------------------------------------
int sub_8048400()
{
  return dword_8049A34();
}
// 8049A34: using guessed type int (*dword_8049A34)(void);

//----- (080484B0) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h] BYREF
  char *retaddr; // [esp+0h] [ebp+0h] BYREF

  v2 = v3;
  v3 = a1;
  __libc_start_main(
    (int (__cdecl *)(int, char **, char **))main,
    v2,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 80484B3: positive sp value 4 has been found

//----- (080484E0) --------------------------------------------------------
void _do_global_dtors_aux()
{
  int v0; // eax
  unsigned int i; // ebx

  if ( !completed_6159 )
  {
    v0 = dtor_idx_6161;
    for ( i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6161 < i; v0 = dtor_idx_6161 )
    {
      dtor_idx_6161 = v0 + 1;
      ((void (*)(void))_DTOR_LIST__[v0 + 1])();
    }
    completed_6159 = 1;
  }
}
// 8049954: using guessed type int _DTOR_LIST__[];
// 8049958: using guessed type int _DTOR_END__;
// 8049AA4: using guessed type char completed_6159;
// 8049AA8: using guessed type int dtor_idx_6161;

//----- (08048540) --------------------------------------------------------
int frame_dummy()
{
  int result; // eax

  result = _JCR_LIST__;
  if ( _JCR_LIST__ )
    return 0;
  return result;
}
// 804995C: using guessed type int _JCR_LIST__;

//----- (08048564) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  char s[5]; // [esp+20h] [ebp-88h] BYREF
  char v5[2]; // [esp+25h] [ebp-83h] BYREF
  char v6[129]; // [esp+27h] [ebp-81h] BYREF

  while ( 1 )
  {
    printf("%p, %p \n", auth, (const void *)service);
    if ( !fgets(s, 128, stdin) )
      break;
    if ( !memcmp(s, "auth ", 5u) )
    {
      auth = (char *)malloc(4u);
      *(_DWORD *)auth = 0;
      if ( strlen(v5) <= 0x1E )
        strcpy(auth, v5);
    }
    if ( !memcmp(s, "reset", 5u) )
      free(auth);
    if ( !memcmp(s, "service", 6u) )
      service = (int)strdup(v6);
    if ( !memcmp(s, "login", 5u) )
    {
      if ( *((_DWORD *)auth + 8) )
        system("/bin/sh");
      else
        fwrite("Password:\n", 1u, 0xAu, stdout);
    }
  }
  return 0;
}
// 8049AB0: using guessed type int service;
// 8048564: using guessed type char anonymous_0[129];

//----- (08048740) --------------------------------------------------------
void __cdecl _libc_csu_init(int a1, int a2, int a3)
{
  int v3; // edi
  int i; // esi

  init_proc();
  v3 = (134519340 - (int)&GLOBAL_OFFSET_TABLE_) >> 2;
  if ( v3 )
  {
    for ( i = 0; i != v3; ++i )
      ((void (__cdecl *)(int, int, int))_CTOR_LIST__[i])(a1, a2, a3);
  }
}
// 804994C: using guessed type int _CTOR_LIST__[];
// 8049A2C: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (080487C0) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
  void (*result)(void); // eax
  void (**v1)(void); // ebx

  result = (void (*)(void))_CTOR_LIST__[0];
  if ( _CTOR_LIST__[0] != -1 )
  {
    v1 = (void (**)(void))_CTOR_LIST__;
    do
    {
      --v1;
      result();
      result = *v1;
    }
    while ( *v1 != (void (*)(void))-1 );
  }
  return result;
}
// 804994C: using guessed type int _CTOR_LIST__[];

//----- (080487EC) --------------------------------------------------------
void term_proc()
{
  _do_global_dtors_aux();
}

// nfuncs=31 queued=9 decompiled=9 lumina nreq=0 worse=0 better=0
// ALL OK, 9 function(s) have been successfully decompiled
